INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Rafael Alberto', 'Mejía Cuello', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Ivonne Offyr', 'Castro Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Mario Alberto', 'Mejía Castro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (2, 'Alexis Rafael', 'Mejía Mendoza', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (2, 'Invitado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (3, 'Ana María', 'Mejía Serna', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (3, 'Ariel Alejandro', 'Rivera Zapata', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Audis María', 'Castro Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (4, 'Félix Alberto', 'Castro Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (4, 'Luz Mary', 'Berdugo Ayola', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (5, 'Yoleida Esther', 'Castro Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (5, 'Deivis José ', 'Feria Castro', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (6, 'Carlos Fernando', 'Hernández Mejía', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (6, 'Nini Johanna', 'Toledo Cano', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (7, 'Miguel Eduardo', 'Noriega Mejía', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (7, 'Adriana', 'Buitrago Aldana', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Javier Mauricio', 'Noriega Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Eduardo', 'Noriega', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Yolanda', 'Mejía Cuello', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Maria Elvira', 'Noriega Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Myriam', 'Mejía Cuello', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Ivan David', 'Domínguez Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Isabeliana', 'Domínguez Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Jordan', 'Aguilar', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (6, 'Helena', 'Mejía Cuello', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (10, 'Jorge Andrés', 'Hernández Mejía', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (10, 'Laura Vanessa', 'Zambrano Mendinueta', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (11, 'Sandra', 'Kleinhaus', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (11, 'Michael', 'Kleinhaus', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (12, 'Cristian Leonardo', 'Echeverría Martin', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (12, 'Laura Juliana ', 'Guerra Niño', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (13, 'Angelica ', 'Rocha Farfan', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (13, 'Diego Fernando', 'Montenegro Forero', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (14, 'Ivone', 'Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (14, 'Carlos', 'Martínez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (14, 'Carlos Andrés', 'Martínez Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (14, 'Valentina', 'Martínez Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (15, 'Carmen Alicia', 'Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (15, 'Armando', 'Sarria', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (16, 'Juan ', 'Liberato', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (17, 'Vivian', 'Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (17, 'William', 'Siado', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (16, 'Sandra ', 'Guayambuco', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (16, 'Artemisa', 'Liberato Guayambuco', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (18, 'Federico ', 'Lafaurie Barros', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (18, 'Yesenia Esther', 'Reales Lopez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (18, 'Bebe Federico', 'Lafaurie Reales', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (19, 'Rafael', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (20, 'Ana Marjorie', 'Pérez', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (20, 'Luís', 'Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (20, 'Luís Augusto', 'Pérez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (21, 'Joana', 'Cunha', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (22, 'Rafael Javier', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (22, 'Kristina', 'Gutsenkova', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (23, 'Liria', 'Gómez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (23, 'Javier ', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (24, 'Milena', 'Villalba', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (24, 'Francisco Javier', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (25, 'Gabriela', 'Lopez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (25, 'Alvaro', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (26, 'Rene', 'Pérez', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (26, 'Emma ', 'Pérez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (27, 'Marie Françoise', 'Royer', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (27, 'António ', 'Oliveira Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (27, 'Inês ', 'Oliveira Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (27, 'Nayan ', 'Oliveira', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (27, 'João Rafael', 'Oliveira Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (28, 'Maria Teresa ', 'Moreira', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (29, 'Luis', 'Silva', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (30, 'Sara', 'Higuchi', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (31, 'Sara Rute ', 'Magalhães', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (32, 'Luz ', 'Le Core', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (32, 'Jean Marie ', 'Le Core', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (33, 'Henrique', 'Costa', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (33, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (33, 'Adriana', 'Costa', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (34, 'Herminia', 'Nascimento', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (35, 'Catarina ', 'Lima', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (35, 'Daniel', 'Zage', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (36, 'Nicoletta', 'Pombares', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (37, 'Ana Margarida', 'Lopes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (37, 'Rita', 'Morais Lopes', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (38, 'Célia Beatriz ', 'Vieira', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (38, 'Emanuel', 'Silva', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (39, 'Mafalda', 'Fidalgo', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (40, 'Maria', 'Cortes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (41, 'Catarina', 'Rebola', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (41, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (42, 'Leonor', 'Sousa', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (42, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (43, 'Bárbara', 'Babo', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (43, 'Nuno', 'Araújo', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (43, 'Cátia', 'Babo', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (43, 'Jesús', 'Castro', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (44, 'Alberto', 'Chillón', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (44, 'Leonardo', 'Lennertz Marcotulio', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (45, 'Beatriz ', 'Figueirinha', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (46, 'Gloria ', 'Miranda', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (46, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (47, 'María João', 'Lopes', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (48, 'João', 'Lopes', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (49, 'Carla', 'Santos', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (21, 'Pedro', 'Cunha', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (21, 'Isabel', 'Cunha', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (50, 'Graciela', 'Calderón', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (50, 'Victor', 'García', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (50, 'Victoria', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (50, 'Vanesa ', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (50, 'Beatriz ', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (51, 'Maria', 'Álvarez', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (52, 'Marta ', 'Santos', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (52, 'Daniel', 'Cabaceira', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (53, 'Carlos ', 'Ribeiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (53, 'Albano', 'Magalhães', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (54, 'Elia ', 'Loureiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (55, 'Tiago ', 'Santos', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (55, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (56, 'Leticia ', 'Correia', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (57, 'Marielba', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (57, 'Pierre', 'Rechou', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (58, 'Abel ', 'Ribeiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (58, 'Vitor ', 'Ribeiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (59, 'Alberto ', 'Miranda', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (59, 'Sofia', 'Ottilino', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (60, 'Pedro ', 'Pérez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (60, 'Samuel', 'Pérez ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (61, 'Miguel', 'Sánchez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (61, 'Lucia ', 'Eugeni', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (62, 'Yane ', 'Acosta ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (63, 'Daniela ', 'Feliciaggi', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (64, 'Maria Fernanda ', 'Pereda', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (65, 'Mariana', 'Rodrigues', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (65, 'David', 'Rocchi', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (66, 'Tiago ', 'Ferraz', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (66, 'Susana', 'Pereira ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (67, 'Mauricio', 'Mejia', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (67, 'Ana', 'Montes', NULL, 0, 0, NULL);