INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Rafael Alberto', 'Mejía Cuello', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Ivonne Offyr', 'Castro Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Mario Alberto', 'Mejía Castro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (2, 'Alexis Rafael', 'Mejía Mendoza', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (2, 'Invitado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (3, 'Ana María', 'Mejía Serna', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (3, 'Ariel Alejandro', 'Rivera Zapata', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (1, 'Audis María', 'Castro Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (4, 'Félix Alberto', 'Castro Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (4, 'Luz Mary', 'Berdugo Ayola', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (5, 'Yoleida Esther', 'Castro Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (5, 'Deivis José ', 'Feria Castro', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (6, 'Carlos Fernando', 'Hernández Mejía', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (6, 'Nini Johanna', 'Toledo Cano', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (7, 'Miguel Eduardo', 'Noriega Mejía', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (7, 'Adriana', 'Buitrago Aldana', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Javier Mauricio', 'Noriega Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Eduardo', 'Noriega', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Yolanda', 'Mejía Cuello', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (8, 'Maria Elvira', 'Noriega Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Myriam', 'Mejía Cuello', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Ivan David', 'Domínguez Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Isabeliana', 'Domínguez Mejía', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (9, 'Jordan', 'Aguilar', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (6, 'Helena', 'Mejía Cuello', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (10, 'Jorge Andrés', 'Hernández Mejía', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (10, 'Laura Vanessa', 'Zambrano Mendinueta', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (11, 'Sandra', 'Kleinhaus', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (11, 'Michael', 'Kleinhaus', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (12, 'Cristian Leonardo', 'Echeverría Martin', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (12, 'Laura Juliana ', 'Guerra Niño', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (13, 'Angelica ', 'Rocha Farfan', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (13, 'Diego Fernando', 'Montenegro Forero', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (14, 'Alfonso ', 'Arias', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (15, 'Ivonne', 'Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (15, 'Carlos', 'Martínez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (15, 'Carlos Andrés', 'Martínez Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (15, 'Valentina', 'Martínez Hernández', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (16, 'Carmen Alicia', 'Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (16, 'Armando', 'Sarria', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (17, 'Juan ', 'Liberato', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (18, 'Vivian', 'Hernández', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (18, 'William', 'Siado', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (17, 'Sandra ', 'Guayambuco', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (17, 'Artemisa', 'Liberato Guayambuco', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (19, 'Federico ', 'Lafaurie Barros', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (19, 'Yesenia Esther', 'Reales Lopez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (19, 'Bebe Federico', 'Lafaurie Reales', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (20, 'Rafael', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (21, 'Ana Marjorie', 'Pérez', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (21, 'Luís', 'Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (21, 'Luís Augusto', 'Pérez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (22, 'Joana', 'Cunha', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (23, 'Rafael Javier', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (23, 'Kristina', 'Gutsenkova', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (24, 'Liria', 'Gómez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (24, 'Javier ', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (25, 'Milena', 'Villalba', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (25, 'Francisco Javier', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (26, 'Gabriela', 'Lopez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (26, 'Alvaro', 'Montes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (27, 'Rene', 'Pérez', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (27, 'Emma ', 'Pérez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (28, 'Marie Françoise', 'Royer', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (28, 'António ', 'Oliveira Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (28, 'Inês ', 'Oliveira Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (28, 'Nayan ', 'Oliveira', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (28, 'João Rafael', 'Oliveira Cruz', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (29, 'Maria Teresa ', 'Moreira', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (30, 'Luis', 'Silva', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (31, 'Sara', 'Higuchi', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (32, 'Sara Rute ', 'Magalhães', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (33, 'Luz ', 'Le Core', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (33, 'Jean Marie ', 'Le Core', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (34, 'Henrique', 'Costa', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (34, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (34, 'Adriana', 'Costa', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (35, 'Herminia', 'Nascimento', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (36, 'Catarina ', 'Lima', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (36, 'Daniel', 'Zage', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (37, 'Nicoletta', 'Pombares', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (38, 'Ana Margarida', 'Lopes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (38, 'Rita', 'Morais Lopes', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (39, 'Célia Beatriz ', 'Vieira', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (39, 'Emanuel', 'Silva', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (40, 'Mafalda', 'Fidalgo', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (41, 'Maria', 'Cortes', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (42, 'Catarina', 'Rebola', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (42, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (43, 'Leonor', 'Sousa', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (43, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (44, 'Bárbara', 'Babo', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (44, 'Nuno', 'Araújo', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (44, 'Cátia', 'Babo', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (44, 'Jesús', 'Castro', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (45, 'Alberto', 'Chillón', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (45, 'Leonardo', 'Lennertz Marcotulio', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (46, 'Beatriz ', 'Figueirinha', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (47, 'Gloria ', 'Miranda', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (47, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (48, 'María João', 'Lopes', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (49, 'João', 'Lopes', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (50, 'Carla', 'Santos', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (22, 'Pedro', 'Cunha', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (22, 'Isabel', 'Cunha', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (51, 'Graciela', 'Calderón', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (51, 'Victor', 'García', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (51, 'Victoria', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (51, 'Vanesa ', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (51, 'Beatriz ', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (52, 'Maria', 'Álvarez', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (53, 'Marta ', 'Santos', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (53, 'Daniel', 'Cabaceira', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (54, 'Carlos ', 'Ribeiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (54, 'Albano', 'Magalhães', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (55, 'Elia ', 'Loureiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (56, 'Tiago ', 'Santos', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (56, 'Convidado', 'Adicional', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (57, 'Leticia ', 'Correia', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (58, 'Marielba', 'García', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (58, 'Pierre', 'Rechou', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (59, 'Abel ', 'Ribeiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (59, 'Vitor ', 'Ribeiro', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (60, 'Alberto ', 'Miranda', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (60, 'Sofia', 'Ottilino', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (61, 'Pedro ', 'Pérez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (61, 'Samuel', 'Pérez ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (62, 'Miguel', 'Sánchez', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (62, 'Lucia ', 'Eugeni', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (63, 'Yane ', 'Acosta ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (64, 'Daniela ', 'Feliciaggi', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (65, 'Maria Fernanda ', 'Pereda', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (66, 'Klaus ', 'Hartfiel', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (67, 'Irina ', 'Capriles ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (68, 'Mariana', 'Rodrigues', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (69, 'Pedro ', 'Rodrigues', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (68, 'David', 'Rocchi', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (70, 'Mario Rui', 'Ferreira', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (70, 'Conceição', 'Ferreira', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (71, 'Albertina', 'Van-Trier', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (71, 'Convidado ', 'Adicional ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (72, 'António ', 'Carvalho', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (72, 'Helia', 'Faria', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (72, 'Sara', 'Faria Carvalho', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (72, 'Sofia', 'Faria Carvalho', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (73, 'Tiago ', 'Ferraz', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (73, 'Susana', 'Pereira ', NULL, 0, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (74, 'Mauricio', 'Mejia', NULL, 1, 0, NULL);
INSERT INTO guest (invitation_id, first_name, last_name, email, is_primary_guest, is_vegetarian, notes) VALUES (74, 'Ana', 'Montes', NULL, 0, 0, NULL);